WEB_PROYECTOS/Controllers/DepartamentoController.cs
using ENTIDAD;
using NEGOCIO;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace WEB_PROYECTOS.Controllers
{
    [Authorize(Roles = "Admin")]
    public class DepartamentoController : Controller
    {
        // GET: Departamento
        public ActionResult Index()
        {
            var dptos = DepartamentoCN.ListaDepartamento();
            return View(dptos);
        }

        [HttpGet]       
        public ActionResult crear()
        {
            return View();
        }
        
        [HttpPost]
        public ActionResult crear(Departamento dpto)
        {
            if (dpto.NombreDepartamento == null)
            {
                ModelState.AddModelError("", "Debe ingresar un Nombre departamento");
                return View(dpto);
            }
            try
            {
                DepartamentoCN.Agregar(dpto);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ModelState.AddModelError("", "Ocurrio un error al agregar");
                return View(dpto);
            }
        }
        public ActionResult GetDepartamento(int id)
        {
            var dpto = DepartamentoCN.GetDepartamento(id);
            return View(dpto);
        }

        public JsonResult GetDepartamentos()
        {
            var lista = DepartamentoCN.ListaDepartamento();
            return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Editar(int id) 
        {
            var dpto = DepartamentoCN.GetDepartamento(id);
            return View(dpto);
        }
        [HttpPost]
        public ActionResult Editar(Departamento dpto)
        {
            try
            {
                if (dpto.NombreDepartamento == null)
                {
                    ModelState.AddModelError("", "Debe ingresar un Nombre departamento");
                    return View(dpto); 
                }
                DepartamentoCN.Editar(dpto);
                return RedirectToAction("Index");
            }
            catch
            {
                ModelState.AddModelError("", "Ocurrio un error al agregar cambio");
                return View(dpto);
            }
        }

        public ActionResult Eliminar(int? id)
        {
            if (id == null)
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            var dpto = DepartamentoCN.GetDepartamento(id.Value);
            return View(dpto);
        }

        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                DepartamentoCN.Eliminar(id);
                return Json(new { ok = true, toRedirect = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

WEB_PROYECTOS/Controllers/EmpleadoController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using ENTIDAD;
using Microsoft.Owin.Security;
using Microsoft.Owin.Security.Provider;
using NEGOCIO;
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB_PROYECTOS.Controllers
{
    [Authorize(Roles ="Admin")]
    public class EmpleadoController : Controller
    {
        // GET: empleado
        public ActionResult Index()
        {
            var empleados = EmpleadoCN.ListarEmpleados();
            return View(empleados);
        }
        [HttpGet]
        public ActionResult Crear()
        {     
            return View();            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Empleado empleado)
        {
            try
            {
                

                System.Threading.Thread.Sleep(1000);
                EmpleadoCN.Agregar(empleado);
                return Json(new { ok = true, toRedirect = "Index" }, JsonRequestBehavior.AllowGet); 
                //return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
                //ModelState.AddModelError("", "Ocurrió un error al agregar un Proyecto");
                //return View();
            }
           
        }
        public ActionResult Detalles(int id)
        {
            var proyecto = EmpleadoCN.ObtenerEmpleado(id);
            return View(proyecto);
        }
        public ActionResult Editar(int id)
        {
            var proyecto = EmpleadoCN.ObtenerEmpleado(id);
            return View(proyecto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Empleado empleado)
        {
            try
            {
                EmpleadoCN.Editar(empleado);
                return Json(new { ok = true, toRedirect = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);

            }

        }
        [HttpPost]
        public ActionResult Eliminar(int identificador)
        {
            try
            {
                EmpleadoCN.Eliminar(identificador);
                return Json(new { ok = true, toRedirect = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ListarEmpleados()
        {
            try
            {
                var lista = EmpleadoCN.ListarEmpleados();
                return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult RptEmpleado()
        {
            return View();
        }

        public ActionResult DescargarReporteEmpleado(int id )
        {
            try
            {
                var rptH = new ReportClass();
                rptH.FileName = Server.MapPath("/Reportes/EmpleadoReporte1.rpt");
                rptH.Load();

                rptH.SetParameterValue("DptoId", id);
                //rptH.SetParameterValue("ParamAlgo", algo);mas de un parametro 

                // Report connection
                var connInfo = CrystalReportsCnn.GetConnectionInfo();
                TableLogOnInfo logonInfo = new TableLogOnInfo();
                Tables tables;
                tables = rptH.Database.Tables;
                foreach (Table table in tables)
                {
                    logonInfo = table.LogOnInfo;
                    logonInfo.ConnectionInfo = connInfo;
                    table.ApplyLogOnInfo(logonInfo);
                }

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();

                //En PDF
                Stream stream = rptH.ExportToStream(ExportFormatType.PortableDocFormat);
                rptH.Dispose();
                rptH.Close();
                return new FileStreamResult(stream, "application/pdf");

                //En Excel
                //Stream stream = rptH.ExportToStream(ExportFormatType.Excel);
                //stream.Seek(0, SeekOrigin.Begin);
                //return File(stream, "application/vnd.ms-excel", "empleadoRpt.xls");
            }
            catch (Exception ex)
            {
                throw;
            }

        }
    }
}

WEB_PROYECTOS/Controllers/ProyectoController.cs
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;
using ENTIDAD;
using Microsoft.Ajax.Utilities;
using Microsoft.Owin.Security;
using NEGOCIO;
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WEB_PROYECTOS.Controllers
{
    //[Authorize(Roles ="Admin")]
    public class ProyectoController : Controller
    {
        // GET: Proyecto
        public ActionResult Index()
        {
            var proyectos = ProyectoCN.ListarProyecto();
            return View(proyectos);
        }
        [HttpGet]
        public ActionResult Crear()
        {     
            return View();            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Crear(Proyecto proyecto)
        {
            try
            {
                if(proyecto.NombreProyecto==null)
                    return Json(new { ok = false, msg = "Debe ingresar el nombre del proyecto" }, JsonRequestBehavior.AllowGet);

                System.Threading.Thread.Sleep(1000);
                ProyectoCN.Agregar(proyecto);
                return Json(new { ok = true, toRedirect = "Index" }, JsonRequestBehavior.AllowGet); 
                //return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
                //ModelState.AddModelError("", "Ocurrió un error al agregar un Proyecto");
                //return View();
            }
           
        }
        public ActionResult Detalles(int id)
        {
            var proyecto = ProyectoCN.ObtenerProyecto(id);
            return View(proyecto);
        }
        public ActionResult Editar(int id)
        {
            var proyecto = ProyectoCN.ObtenerProyecto(id);
            return View(proyecto);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Proyecto proyecto)
        {
            try
            {
                System.Threading.Thread.Sleep(1000);
                ProyectoCN.Editar(proyecto);
                return Json(new { ok = true, toRedirect = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
                
            }
            
        }
        [HttpPost]
        public ActionResult Eliminar(int id)
        {
            try
            {
                ProyectoCN.Eliminar(id);
                return Json(new { ok = true, toRedirect = Url.Action("Index") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult ListarProyectos()
        {
            try
            {
                var lista = ProyectoCN.ListarProyecto();
                return Json(new { data = lista }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AsignarProyecto()
        {
            return View(ProyectoCN.ListasAsignaciones());
        }

        [HttpPost]
        public ActionResult AsignarProyecto(int proyectoId, int empleadoId)
        {
            try
            {
                if (ProyectoCN.ExisteAsignacion(proyectoId, empleadoId))
                    return Json(new { ok = false, msg = "Ya existe una relación entre este proyecto y el empleado" });

                if (!ProyectoCN.EsProyectoActivo(proyectoId))
                    return Json(new { ok = false, msg = "El proyecto ya no se encuentra activo." });


                ProyectoCN.AsignarProyecto(proyectoId, empleadoId);
                return Json(new { ok = true, toRedirect = Url.Action("AsignarProyecto") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }

        [HttpPost]
        public ActionResult EliminarAsignacion(int proyectoId, int empleadoId)
        {
            try
            {
                ProyectoCN.EliminarAsignacion(proyectoId, empleadoId);
                return Json(new { ok = true, toRedirect = Url.Action("AsignarProyecto") }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {

                return Json(new { ok = false, msg = ex.Message }, JsonRequestBehavior.AllowGet);
            }
        }
        public ActionResult RptProyecto()
        {
            return View();
        }

        public ActionResult DescargarReporteProyectos()
        {
            try
            {
                var proyectos = ProyectoCN.ListarProyecto();

                var rptH = new ReportClass();
                rptH.FileName = Server.MapPath("/Reportes/ProyectoListas.rpt");
                rptH.Load();

                rptH.SetDataSource(proyectos);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();

                //En PDF
                Stream stream = rptH.ExportToStream(ExportFormatType.PortableDocFormat);
                rptH.Dispose();
                rptH.Close();
                return new FileStreamResult(stream, "application/pdf");
            }
            catch (Exception ex)
            {

                throw;
            }
        }

        public ActionResult RptAsignacion()
        {
            return View();
        }

        public ActionResult DescargarReporteAsignaciones(int? id)
        {
            try
            {
                //var asignaciones = ProyectoCN.ListasAsignaciones();

                var rptH = new ReportClass();
                rptH.FileName = Server.MapPath("/Reportes/AsignacionReport1.rpt");
                rptH.Load();

                if (id == null)
                    rptH.SetDataSource(ProyectoCN.ListasAsignaciones());
                else
                    rptH.SetDataSource(ProyectoCN.ListasAsignaciones(id.Value));

                //rptH.SetDataSource(asignaciones);

                Response.Buffer = false;
                Response.ClearContent();
                Response.ClearHeaders();

                //En PDF
                Stream stream = rptH.ExportToStream(ExportFormatType.PortableDocFormat);
                rptH.Dispose();
                rptH.Close();
                return new FileStreamResult(stream, "application/pdf");
            }
            catch (Exception ex)
            {

                throw;
            }
        }

    }
}

WEB_PROYECTOS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Nombre de la aplicación", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Departamentos", "Index", "Departamento", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Empleados", "Index", "Empleado", new { area = "" }, new { @class = "nav-link" })</li>
                    <li class="dropdown">
                        <a href="#" class="nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Proyectos <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu"  class="dropdown">
                            <li><a href="#">@Html.ActionLink("CRUD Proyectos", "Index", "Proyecto")</a></li>
                            <li role="separator" class="divider"></li>
                            <li><a href="#">@Html.ActionLink("Asignar Proyectos", "AsignarProyecto", "Proyecto")</a></li>
                        </ul>
                    </li>
                    <li class="dropdown">
                        <a href="#" class="nav-link" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            Reportes <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="#">@Html.ActionLink("Rpt Empleados", "RptEmpleado", "Empleado")</a></li>
                            <li><a href="#">@Html.ActionLink("Rpt Proyectos", "RptProyecto", "Proyecto")</a></li>
                            <li><a href="#">@Html.ActionLink("Rpt Asignaciones", "RptAsignacion", "Proyecto")</a></li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/gasparesganga-jquery-loading-overlay@2.1.7/dist/loadingoverlay.min.js"></script>
    <script src="//cdn.datatables.net/2.0.1/js/dataTables.min.js"></script>
    <script src="~/Scripts/app.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.4/jquery-confirm.min.css">
    <link href="//cdn.datatables.net/2.0.1/css/dataTables.dataTables.min.css" rel="stylesheet" />
    @RenderSection("scripts", required: false)
</body>
</html>